// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNB8IErdepz3btJ8CbWw72oSRBpCiT0g0',
    appId: '1:332437452947:web:b9f09a36af5e38ea297566',
    messagingSenderId: '332437452947',
    projectId: 'smartscan-mlkit-c2182',
    authDomain: 'smartscan-mlkit-c2182.firebaseapp.com',
    storageBucket: 'smartscan-mlkit-c2182.firebasestorage.app',
    measurementId: 'G-03KKX51C9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeWhA6h-JFkfMn-DKnttOPjAHei1WSA4',
    appId: '1:332437452947:android:14352f4afc41f756297566',
    messagingSenderId: '332437452947',
    projectId: 'smartscan-mlkit-c2182',
    storageBucket: 'smartscan-mlkit-c2182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7v05BT_oQMZtBZhKCQH7G__o2J-Ca2s',
    appId: '1:332437452947:ios:c796dfeeb329ca18297566',
    messagingSenderId: '332437452947',
    projectId: 'smartscan-mlkit-c2182',
    storageBucket: 'smartscan-mlkit-c2182.firebasestorage.app',
    iosBundleId: 'com.example.smartscanMlkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD7v05BT_oQMZtBZhKCQH7G__o2J-Ca2s',
    appId: '1:332437452947:ios:c796dfeeb329ca18297566',
    messagingSenderId: '332437452947',
    projectId: 'smartscan-mlkit-c2182',
    storageBucket: 'smartscan-mlkit-c2182.firebasestorage.app',
    iosBundleId: 'com.example.smartscanMlkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNB8IErdepz3btJ8CbWw72oSRBpCiT0g0',
    appId: '1:332437452947:web:ee6b3b05acdfe7d8297566',
    messagingSenderId: '332437452947',
    projectId: 'smartscan-mlkit-c2182',
    authDomain: 'smartscan-mlkit-c2182.firebaseapp.com',
    storageBucket: 'smartscan-mlkit-c2182.firebasestorage.app',
    measurementId: 'G-HJLJ1XHV40',
  );
}
