class AppLocalizations {
  static const Map<String, Map<String, String>> _values = {
    'fr': {
      'home': 'Accueil',
      'documents': 'Documents',
      'scan': 'Scan',
      'result': 'Resultat',
      'history': 'Historique',
      'settings': 'Parametres',
      'welcome': 'Bienvenue',
      'homeDescription':
          'Cette application permet de scanner un document, extraire le texte, identifier la langue et preparer la traduction.',
      'serviceOcrTitle': 'Service 1: OCR',
      'serviceOcrSubtitle': 'Reconnaissance de texte a partir d image',
      'serviceLanguageTitle': 'Service 2: Language ID',
      'serviceLanguageSubtitle':
          'Traduction automatique du resultat (FR/EN/AR)',
      'detectedText': 'Texte detecte',
      'detectedLanguages': 'Langues detectees',
      'detectedLanguage': 'Langue detectee',
      'noResult': 'Aucun resultat pour le moment. Lance un scan.',
      'ocrProcessing': 'Traitement OCR en cours...',
      'scanStep': 'Etape suivante: connecter la camera/galerie et lancer OCR.',
      'selectedImage': 'Image choisie',
      'darkMode': 'Mode sombre',
      'appLanguage': 'Langue de l application',
      'historyItem': 'Scan',
      'historyEmpty': 'Aucun enregistrement pour le moment',
      'notifications': 'Notifications',
      'sounds': 'Sons',
      'vibration': 'Vibration',
      'notificationsSetupSubtitle':
          'Activez les rappels systeme, le son et la vibration.',
      'feedbackPreviewTitle': 'Tester le son et la vibration',
      'feedbackPreviewSubtitle':
          'Verifie le retour tactile et sonore de l application.',
      'notificationTestActionTitle': 'Envoyer une notification de test',
      'notificationTestActionSubtitle':
          'Affiche une vraie notification systeme sur votre telephone.',
      'notificationPermissionDenied': 'Permission de notification refusee.',
      'notificationTestSent': 'Notification de test envoyee.',
      'notificationReminderTitle': 'SmartScan pense a vous',
      'notificationReminderBody':
          'Revenez scanner un document ou revoir vos resultats.',
      'notificationTestTitle': 'Notification SmartScan',
      'notificationTestBody':
          'Le systeme de notifications, le son et la vibration sont actifs.',
      'webNoSoundVibration':
          'Inactif sur navigateur Web. Fonctionne sur Android / iOS (appareil reel).',
      'captureDocument': 'Capture du document',
      'pickGallery': 'Choisir depuis la galerie',
      'takePhoto': 'Prendre une photo',
      'processing': 'Traitement...',
      'ocrSuccess': 'OCR termine avec succes.',
      'scanCancelled': 'Selection annulee.',
      'geminiApiKey': 'Cle API Gemini',
      'geminiApiKeyHint': 'Collez la cle API pour l analyse medicale IA.',
      'sectionPreferences': 'Preferences',
      'sectionNotifications': 'Notifications',
      'sectionAi': 'Intelligence artificielle',
      'pasteFromClipboard': 'Coller',
      'homeHeroSubtitle':
          'Scannez vos analyses medicales et obtenez un resultat clair, traduisible et exportable.',
      'exportPdf': 'Exporter PDF',
      'viewRawOcr': 'Voir le texte OCR brut',
      'shareAgain': 'Partager a nouveau',
      'analyzeGeminiPdf': 'Analyser (Gemini) et generer PDF',
      'analyzingGemini': 'Analyse Gemini en cours...',
      'addGeminiKeyFirst': 'Ajoutez d abord la cle API Gemini dans Parametres.',
      'noOcrText': 'Aucun texte OCR a analyser.',
      'analysisDonePdfGenerated': 'Analyse terminee et PDF genere.',
      'errorGeminiAnalysis': 'Erreur analyse Gemini',
      'errorPdfExport': 'Erreur export PDF',
      'structuredPdfExported': 'PDF structure exporte.',
      'geminiKeyRequiredTitle': 'Cle Gemini requise',
      'geminiKeyRequiredSubtitle': 'Configurez-la dans les Parametres.',
      'infoPatientMedecin': 'Informations patient et medecin',
      'labelPatient': 'Patient',
      'labelMedecin': 'Medecin',
      'labelDateField': 'Date',
      'analysisResultsTitle': 'Resultats d analyses',
      'noReliableAnalysis': 'Aucune analyse fiable extraite.',
      'colAnalysis': 'Analyse',
      'colValue': 'Valeur',
      'colUnit': 'Unite',
      'rawOcrDialogTitle': 'Texte OCR brut',
      'close': 'Fermer',
      'resultAiSummary': 'Resume IA',
      'resultAiRecommendations': 'Recommandations',
      'resultAiImportant': 'Elements importants',
      'medicalPdfShareSubject': 'Rapport medical SmartScan',
      'importPdf': 'Importer PDF',
      'historySectionTitle': 'Historique des scans',
      'historyEmptySubtitle':
          'Vos scans apparaitront ici apres votre premier document.',
      'clearHistory': 'Effacer l historique',
      'clearHistorySubtitle': 'Supprime tous les scans enregistres',
      'clearHistoryConfirm': 'Cette action est irreversible. Continuer ?',
      'cancel': 'Annuler',
      'confirm': 'Supprimer',
      'historyCleared': 'Historique efface.',
      'scanCount': '{n} scan(s) enregistre(s)',
      'scanEmptyHint':
          'Prenez une photo d un document medical ou importez un PDF pour extraire le texte automatiquement.',
      'geminiOptionalSectionTitle': 'Analyse IA (optionnel)',
      'geminiOptionalSectionSubtitle':
          'Resume Gemini et export PDF si vous configurez une cle API dans Parametres.',
      'historyOcrBrut': 'Texte OCR brut',
      'medicalPatientInfoTitle': 'Informations patient',
      'medicalDocInfoTitle': 'Informations document',
      'labelDossier': 'Dossier',
      'labelOrganisme': 'Organisme',
      'labelLaboratoire': 'Laboratoire',
      'labelRequester': 'Demandeur',
      'labelValidator': 'Validateur',
      'labelReportDate': 'Date rapport',
      'labelSampleDate': 'Date prelevement',
      'labelExamNumber': 'Numero examen',
      'scanErrorImage': 'Erreur lors du traitement de l image',
      'scanError': 'Erreur',
      'scanPdfUnreadable': 'Impossible de lire le PDF selectionne.',
      'scanPdfImport': 'Erreur import PDF',
      'ocrUnknownError': 'Erreur OCR inconnue.',
      'guidedPhotoModeTitle': 'Mode photo guidee',
      'guidedPhotoModeSubtitle':
          'Controle flou/luminosite + recadrage auto avant OCR.',
      'guidedPhotoReport': 'Photo guidee',
      'guidedCropApplied': 'Recadrage document applique',
    },
    'en': {
      'home': 'Home',
      'documents': 'Documents',
      'scan': 'Scan',
      'result': 'Result',
      'history': 'History',
      'settings': 'Settings',
      'welcome': 'Welcome',
      'homeDescription':
          'This app scans a document, extracts text, detects language and prepares translation.',
      'serviceOcrTitle': 'Service 1: OCR',
      'serviceOcrSubtitle': 'Text recognition from an image',
      'serviceLanguageTitle': 'Service 2: Language ID',
      'serviceLanguageSubtitle': 'Automatic result translation (FR/EN/AR)',
      'detectedText': 'Detected text',
      'detectedLanguages': 'Detected languages',
      'detectedLanguage': 'Detected language',
      'noResult': 'No result yet. Start a scan.',
      'ocrProcessing': 'OCR processing...',
      'scanStep': 'Next step: connect camera/gallery and run OCR.',
      'selectedImage': 'Selected image',
      'darkMode': 'Dark mode',
      'appLanguage': 'Application language',
      'historyItem': 'Scan',
      'historyEmpty': 'No records yet',
      'notifications': 'Notifications',
      'sounds': 'Sounds',
      'vibration': 'Vibration',
      'notificationsSetupSubtitle':
          'Enable system reminders, sound and vibration feedback.',
      'feedbackPreviewTitle': 'Test sound and vibration',
      'feedbackPreviewSubtitle':
          'Preview the tap sound and haptic response used by the app.',
      'notificationTestActionTitle': 'Send a test notification',
      'notificationTestActionSubtitle':
          'Shows a real system notification on your phone.',
      'notificationPermissionDenied': 'Notification permission was denied.',
      'notificationTestSent': 'Test notification sent.',
      'notificationReminderTitle': 'SmartScan is checking in',
      'notificationReminderBody':
          'Come back to scan a document or review your results.',
      'notificationTestTitle': 'SmartScan notification',
      'notificationTestBody':
          'Notifications, sound and vibration are ready on this device.',
      'webNoSoundVibration':
          'Not available in the web browser. Works on Android / iOS (real device).',
      'captureDocument': 'Document capture',
      'pickGallery': 'Choose from gallery',
      'takePhoto': 'Take a photo',
      'processing': 'Processing...',
      'ocrSuccess': 'OCR completed successfully.',
      'scanCancelled': 'Selection cancelled.',
      'geminiApiKey': 'Gemini API key',
      'geminiApiKeyHint': 'Paste API key for medical AI analysis.',
      'sectionPreferences': 'Preferences',
      'sectionNotifications': 'Notifications',
      'sectionAi': 'Artificial intelligence',
      'pasteFromClipboard': 'Paste',
      'homeHeroSubtitle':
          'Scan medical reports and get clear, translatable, exportable results.',
      'exportPdf': 'Export PDF',
      'viewRawOcr': 'View raw OCR text',
      'shareAgain': 'Share again',
      'analyzeGeminiPdf': 'Analyze (Gemini) and generate PDF',
      'analyzingGemini': 'Gemini analysis in progress...',
      'addGeminiKeyFirst': 'Add your Gemini API key in Settings first.',
      'noOcrText': 'No OCR text to analyze.',
      'analysisDonePdfGenerated': 'Analysis complete and PDF generated.',
      'errorGeminiAnalysis': 'Gemini analysis error',
      'errorPdfExport': 'PDF export error',
      'structuredPdfExported': 'Structured PDF exported.',
      'geminiKeyRequiredTitle': 'Gemini key required',
      'geminiKeyRequiredSubtitle': 'Configure it in Settings.',
      'infoPatientMedecin': 'Patient and physician information',
      'labelPatient': 'Patient',
      'labelMedecin': 'Physician',
      'labelDateField': 'Date',
      'analysisResultsTitle': 'Test results',
      'noReliableAnalysis': 'No reliable analyses extracted.',
      'colAnalysis': 'Test',
      'colValue': 'Value',
      'colUnit': 'Unit',
      'rawOcrDialogTitle': 'Raw OCR text',
      'close': 'Close',
      'resultAiSummary': 'AI summary',
      'resultAiRecommendations': 'Recommendations',
      'resultAiImportant': 'Important findings',
      'medicalPdfShareSubject': 'SmartScan medical report',
      'importPdf': 'Import PDF',
      'historySectionTitle': 'Scan history',
      'historyEmptySubtitle':
          'Your scans will appear here after your first document.',
      'clearHistory': 'Clear history',
      'clearHistorySubtitle': 'Delete all saved scans',
      'clearHistoryConfirm': 'This action cannot be undone. Continue?',
      'cancel': 'Cancel',
      'confirm': 'Delete',
      'historyCleared': 'History cleared.',
      'scanCount': '{n} scan(s) saved',
      'scanEmptyHint':
          'Take a photo of a medical document or import a PDF to extract text automatically.',
      'geminiOptionalSectionTitle': 'Optional AI analysis',
      'geminiOptionalSectionSubtitle':
          'Gemini summary and PDF export when you add an API key in Settings.',
      'historyOcrBrut': 'Raw OCR text',
      'medicalPatientInfoTitle': 'Patient information',
      'medicalDocInfoTitle': 'Document information',
      'labelDossier': 'File no.',
      'labelOrganisme': 'Organization',
      'labelLaboratoire': 'Laboratory',
      'labelRequester': 'Requesting physician',
      'labelValidator': 'Validator',
      'labelReportDate': 'Report date',
      'labelSampleDate': 'Sample date',
      'labelExamNumber': 'Exam number',
      'scanErrorImage': 'Error while processing the image',
      'scanError': 'Error',
      'scanPdfUnreadable': 'Could not read the selected PDF.',
      'scanPdfImport': 'PDF import error',
      'ocrUnknownError': 'Unknown OCR error.',
      'guidedPhotoModeTitle': 'Guided photo mode',
      'guidedPhotoModeSubtitle':
          'Blur/light checks + auto document crop before OCR.',
      'guidedPhotoReport': 'Guided photo',
      'guidedCropApplied': 'Document auto-crop applied',
    },
    'ar': {
      'home': 'الرئيسية',
      'documents': 'المستندات',
      'scan': 'المسح',
      'result': 'النتيجة',
      'history': 'السجل',
      'settings': 'الإعدادات',
      'welcome': 'مرحبا',
      'homeDescription':
          'هذا التطبيق يمسح المستند ويستخرج النص ويكتشف اللغة ويجهز الترجمة.',
      'serviceOcrTitle': 'الخدمة 1: OCR',
      'serviceOcrSubtitle': 'استخراج النص من الصورة',
      'serviceLanguageTitle': 'الخدمة 2: تحديد اللغة',
      'serviceLanguageSubtitle': 'ترجمة تلقائية للنتيجة (فرنسي/إنجليزي/عربي)',
      'detectedText': 'النص المستخرج',
      'detectedLanguages': 'اللغات المكتشفة',
      'detectedLanguage': 'اللغة المكتشفة',
      'noResult': 'لا توجد نتيجة حاليا. ابدأ عملية مسح.',
      'ocrProcessing': 'جاري استخراج النص...',
      'scanStep': 'الخطوة التالية: اختر الكاميرا/المعرض ثم ابدأ OCR.',
      'selectedImage': 'الصورة المختارة',
      'darkMode': 'الوضع الداكن',
      'appLanguage': 'لغة التطبيق',
      'historyItem': 'عملية مسح',
      'historyEmpty': 'لا توجد سجلات حاليا',
      'notifications': 'الإشعارات',
      'sounds': 'الأصوات',
      'vibration': 'الاهتزاز',
      'webNoSoundVibration':
          'غير متاح في المتصفح. يعمل على أندرويد / iOS (هاتف حقيقي).',
      'captureDocument': 'التقاط المستند',
      'pickGallery': 'اختر من المعرض',
      'takePhoto': 'التقاط صورة',
      'processing': 'جاري المعالجة...',
      'ocrSuccess': 'اكتمل استخراج النص بنجاح.',
      'scanCancelled': 'تم إلغاء الاختيار.',
      'geminiApiKey': 'مفتاح Gemini API',
      'geminiApiKeyHint': 'ألصق مفتاح API لتحليل طبي بالذكاء الاصطناعي.',
      'sectionPreferences': 'التفضيلات',
      'sectionNotifications': 'الإشعارات',
      'sectionAi': 'الذكاء الاصطناعي',
      'pasteFromClipboard': 'لصق',
      'homeHeroSubtitle':
          'امسح التحاليل الطبية واحصل على نتيجة واضحة قابلة للترجمة والتصدير.',
      'exportPdf': 'تصدير PDF',
      'viewRawOcr': 'عرض نص OCR الخام',
      'shareAgain': 'مشاركة مرة أخرى',
      'analyzeGeminiPdf': 'تحليل (Gemini) وإنشاء PDF',
      'analyzingGemini': 'جاري التحليل بـ Gemini...',
      'addGeminiKeyFirst': 'أضف مفتاح Gemini في الإعدادات أولاً.',
      'noOcrText': 'لا يوجد نص OCR للتحليل.',
      'analysisDonePdfGenerated': 'اكتمل التحليل وتم إنشاء PDF.',
      'errorGeminiAnalysis': 'خطأ في تحليل Gemini',
      'errorPdfExport': 'خطأ في تصدير PDF',
      'structuredPdfExported': 'تم تصدير PDF المنظم.',
      'geminiKeyRequiredTitle': 'مفتاح Gemini مطلوب',
      'geminiKeyRequiredSubtitle': 'اضبطه من الإعدادات.',
      'infoPatientMedecin': 'معلومات المريض والطبيب',
      'labelPatient': 'المريض',
      'labelMedecin': 'الطبيب',
      'labelDateField': 'التاريخ',
      'analysisResultsTitle': 'نتائج التحاليل',
      'noReliableAnalysis': 'لم يُستخرج تحليل موثوق.',
      'colAnalysis': 'التحليل',
      'colValue': 'القيمة',
      'colUnit': 'الوحدة',
      'rawOcrDialogTitle': 'نص OCR الخام',
      'close': 'إغلاق',
      'resultAiSummary': 'ملخص الذكاء الاصطناعي',
      'resultAiRecommendations': 'التوصيات',
      'resultAiImportant': 'عناصر مهمة',
      'medicalPdfShareSubject': 'تقرير طبي SmartScan',
      'importPdf': 'استيراد PDF',
      'historySectionTitle': 'سجل المسح',
      'historyEmptySubtitle': 'ستظهر عمليات المسح هنا بعد أول مستند.',
      'clearHistory': 'مسح السجل',
      'clearHistorySubtitle': 'حذف كل عمليات المسح المحفوظة',
      'clearHistoryConfirm':
          'هذا الإجراء لا يمكن التراجع عنه. هل تريد المتابعة؟',
      'cancel': 'إلغاء',
      'confirm': 'حذف',
      'historyCleared': 'تم مسح السجل.',
      'scanCount': '{n} عملية مسح محفوظة',
      'scanEmptyHint':
          'التقط صورة لمستند طبي أو استورد ملف PDF لاستخراج النص تلقائياً.',
      'geminiOptionalSectionTitle': 'تحليل بالذكاء الاصطناعي (اختياري)',
      'geminiOptionalSectionSubtitle':
          'ملخص Gemini وتصدير PDF عند إضافة مفتاح API في الإعدادات.',
      'historyOcrBrut': 'نص OCR الخام',
      'medicalPatientInfoTitle': 'معلومات المريض',
      'medicalDocInfoTitle': 'معلومات المستند',
      'labelDossier': 'رقم الملف',
      'labelOrganisme': 'الجهة',
      'labelLaboratoire': 'المختبر',
      'labelRequester': 'الطبيب الطالب',
      'labelValidator': 'المعتمد',
      'labelReportDate': 'تاريخ التقرير',
      'labelSampleDate': 'تاريخ العينة',
      'labelExamNumber': 'رقم الفحص',
      'scanErrorImage': 'خطأ أثناء معالجة الصورة',
      'scanError': 'خطأ',
      'scanPdfUnreadable': 'تعذّر قراءة ملف PDF المحدد.',
      'scanPdfImport': 'خطأ في استيراد PDF',
      'ocrUnknownError': 'خطأ OCR غير معروف.',
      'guidedPhotoModeTitle': 'وضع الصورة الموجّهة',
      'guidedPhotoModeSubtitle':
          'فحص الضبابية والإضاءة مع قص تلقائي للمستند قبل OCR.',
      'guidedPhotoReport': 'الصورة الموجهة',
      'guidedCropApplied': 'تم تطبيق القص التلقائي للمستند',
    },
  };

  static String t(String localeCode, String key) {
    return _values[localeCode]?[key] ?? _values['fr']![key] ?? key;
  }

  static String languageName(String localeCode) {
    switch (localeCode) {
      case 'en':
        return 'English';
      case 'ar':
        return 'العربية';
      default:
        return 'Francais';
    }
  }

  static String detectedLanguageLabel(String code) {
    switch (code) {
      case 'en':
        return 'English';
      case 'ar':
        return 'العربية';
      case 'fr':
        return 'Francais';
      default:
        return 'Unknown/Inconnue';
    }
  }
}
